package mihon.core.migration.migrations

import mihon.core.migration.Migration

val migrations: List<Migration>
    get() = listOf(
        SetupBackupCreateMigration(),
        SetupAnimeLibraryUpdateMigration(),
        SetupMangaLibraryUpdateMigration(),
        TrustExtensionRepositoryMigration(),
        InternalChapterCacheDirMigration(),
        CoverToExternalFileMigration(),
        DeleteExternalChapterCacheDirMigration(),
        ResetSortPreferenceRemovedMigration(),
        MigrateToTriStateMigration(),
        ForceMALLogOutMigration(),
        DOHMigration(),
        ResetRotationMigration(),
        MigrateRotationViewerValuesMigration(),
        RemoveOneTwoHourUpdateMigration(),
        SetupBackgroundTasksMigration(),
        MigrateSortingModeMigration(),
        AddAllLangMigration(),
        RemoveQuickUpdateMigration(),
        CombineUpdateRestrictionMigration(),
        MigrateSecureScreenMigration(),
        RemoveReaderTapMigration(),
        RenameEnumMigration(),
        MergeSortTypeDirectionMigration(),
        EnableAutoBackupMigration(),
        MoveChapterPreferencesMigration(),
        SplitPreferencesMigration(),
        PlayerPreferenceMigration(),
        MovePlayerPreferencesMigration(),
        UseWorkManagerMigration(),
        RemoveBackgroundJobsMigration(),
        MigrateTriStateMigration(),
        DontRunJobsMigration(),
        RelativeTimestampMigration(),
        NoAppStateMigration(),
        ExternalRepoMigration(),
        PrivatePreferenceMigration(),
        PermaTrustExtensionsMigration(),
        NavigationOptionsMigration(),
        LogOutMALMigration(),
        EnumsMigration(),
        VideoPlayerPreferenceMigration(),
        VideoOrientationMigration(),
        CategoryPreferencesCleanupMigration(),
        PrefLangMigration(),
        AuroraSectionMigration(),
        SetupNovelLibraryUpdateMigration(),
        CoalesceLibraryUpdateWorkersMigration(),
        NavigationTransitionModeMigration(),
        DefaultChapterEpisodeSortNumberMigration(),
        DefaultChapterSortAscendingMigration(),
        EInkProfileMigration(),
        MoveLatestToFeedMigration(),
        RecomputeGenreAchievementsMigration(),
    )
